// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using SetupEntityFrameworkCoreApp.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace SetupEntityFrameworkCoreApp.Data
{
    public partial interface IContextProcedures
    {
        Task<List<usp_SelectCatCountryContactTypeResult>> usp_SelectCatCountryContactTypeAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<uspCustomersOrderByResult>> uspCustomersOrderByAsync(string orderby, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<uspSupplierForProductResult>> uspSupplierForProductAsync(int? productIdentifier, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
