// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SetupEntityFrameworkCoreApp.Models
{
    public partial class uspCustomersOrderByResult
    {
        public int CustomerIdentifier { get; set; }
        [StringLength(40)]
        public string CompanyName { get; set; }
    }
}
